theme: jekyll-theme-minimal

title       : "Daniel Morales"
name        : "Daniel Morales"
description : "Mathematician, statistician, programmer and gamer whenever possible =]"

favicon     : favicon.ico
